### ISSUE TITLE
Cupola

### ISSUE THREAD

**Issue by LouisB3** [LouisB3/HabTech-Classic#4]
- [x] Reduce cost to 1600 (half of stock cupola; slightly more than Mk1 Lander Can)
- [x] Add shutterless variant as a separate part with identical stats, to allow choice between stockalike and ISS-alike versions. Requires redistribution of assets from earlier version of base mod

**Comment by GonDragon** [comment]
I Think that we also should remove the capability of the Cupola of being a command module. It's smaller and lighter than a Mk1 Command Pod, and have even more EC than one. The only downside is that it did not resist as much heat.

Here, a comparation between an MK1 Command Pod, the Cupola from this mod, and a Cupola from USI-LS (Crew capable, but not a command module).
![comparation](https://cloud.githubusercontent.com/assets/7538144/26654522/81709e4a-462d-11e7-8042-1afbbaab904f.png)

**Comment by LouisB3** [comment]
Weight is equivalent to a Mk1 Lander Can. The other stats are pretty modest: 200 EC only represents a mass of 10kg, plus it doesn't have any reaction wheels or a hatch. I am inclined to retain the command capability as it keeps the part more interesting.

I didn't see any other command modules (or EC storage) in the mod though, so I'm actually mulling adding ModuleCommand to other parts - the Z1 truss might make for a good probe core, for example.

**Comment by GonDragon** [comment]
I still thinking that the Cupola shouldn't be a Command Module, but I guess I can ripoff that characteristic for my personal gameplay.

Now, I agree that this mod needs another control module, and the Z1 looks like the right choice. It could be a probe core instead of a command module, so it could mantain the station stable with his SAS, even when there are no Kerbals inside.
